package edu.api.model.security.enums;

public enum CryptoName {
    ALICEUSDT, MATICUSDT, AXSUSDT, AAVEUSDT, ATOMUSDT, NEOUSDT, DOTUSDT, ETHUSDT, CAKEUSDT, BTCUSDT, BNBUSDT, ADAUSDT, TRXUSDT, AUDIOUSDT
    }
